
title: Nicolas Young # your name (or website title) here
logo: "/images/Glogo2.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  High School Intern at UCSF - Summer 2019
  <br><br>
  Captain of Galileo Robotics - 2019-2020 
  <br><br>
  <a href="https://www.linkedin.com/in/nicolas-young-3a1172174/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
