
title: Cassie Young # your name (or website title) here
logo: "/images/IMG_9756.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  College student at University of California, Berkeley, majoring in mechanical engineering and minoring in data science.
  <br><br>
  R&D Intern @ Robotics Cats - Summer 2022<br>
  Systems Lead @ <a href = "https://stars.berkeley.edu/">STAR</a> - 2022—<br>
  Recovery Team Member @ STAR - 2021—<br>
  Stage Sep Team Member @ STAR - 2021—<br>
  Treasurer @ Underwater Robotics at Berkeley - 2021-2022<br>
  <br>
  
  <br><br>
  <a href="https://www.linkedin.com/in/cassie-young-3a1172174/">View My LinkedIn Profile</a> <br>
  
theme: jekyll-theme-minimal
