
title: Nicolas Young # your name (or website title) here
logo: "/images/glogo-100x100.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  High school student at Galileo Academy of Science and Technology (Galileo High School), pursuing a career in mechanical engineering. Interested in computer science and robotics.
  <br><br>
  High School Intern at UCSF - Summer 2019
  <br>
  Captain of Galileo Robotics - 2019-2020 
  <br><br>
  <a href="https://www.linkedin.com/in/nicolas-young-3a1172174/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
