
title: Cassie Young # your name (or website title) here
# logo: "/images/1650151508178.jfif" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  College student at University of California, Berkeley, majoring in mechanical engineering and minoring in data science.
  <br><br>
  R&D Intern @ Robotics Cats - Summer 2022<br>
  Recovery Team Member @ STAR - 2021—<br>
  Stage Sep Team Member @ STAR - 2021—<br>
  Treasurer @ Underwater Robotics at Berkeley - 2021-2022<br>
  Captain @ Galileo Robotics - 2019-2020 <br>
  High School Intern @ UCSF - Summer 2019
  <br>
  
  <br><br>
  <a href="https://www.linkedin.com/in/cassie-young-3a1172174/">View My LinkedIn Profile</a> <br>
  
theme: jekyll-theme-minimal
